# Crie um pipeline para uma aplicação .Net 6 em GitHub Actions
name: .NET 6
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore 

    - name: Publish
      run: dotnet publish --no-restore --no-build --output ./publish
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish             